[dotfiles]
src.git = "https://github.com/yuys13/dotfiles"
src.branch = "main"
fetch.github = "yuys13/dotfiles"

[fish-ghq]
src.git = "https://github.com/decors/fish-ghq"
src.branch = "master"
fetch.github = "decors/fish-ghq"

[fish-autols]
src.git = "https://github.com/yuys13/autols.fish"
src.branch = "main"
fetch.github = "yuys13/autols.fish"

[fish-gcd]
src.git = "https://github.com/yuys13/gcd.fish"
src.branch = "main"
fetch.github = "yuys13/gcd.fish"

[fish-bd]
src.git = "https://github.com/0rax/fish-bd"
src.branch = "master"
fetch.github = "0rax/fish-bd"

