# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dotfiles = {
    pname = "dotfiles";
    version = "7f414819fac660641f1e7ebd8c2b7d31f38c7e56";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "dotfiles";
      rev = "7f414819fac660641f1e7ebd8c2b7d31f38c7e56";
      fetchSubmodules = false;
      sha256 = "sha256-BjVAm1QwFJpeQS8w6OtJaUMujo3hZsGisbnNEmiu85E=";
    };
    date = "2024-09-11";
  };
  fish-autols = {
    pname = "fish-autols";
    version = "5bad7d5fd1bfa187006f1cec6b7016890cbd1e2f";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "autols.fish";
      rev = "5bad7d5fd1bfa187006f1cec6b7016890cbd1e2f";
      fetchSubmodules = false;
      sha256 = "sha256-v2lrurz28qMmChKj8S1ZY65xOn6U0tHBTDjSK4xD6tY=";
    };
    date = "2024-09-07";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  fish-gcd = {
    pname = "fish-gcd";
    version = "b3e35ab0852d6779403ada84b1f1be03692f507a";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "gcd.fish";
      rev = "b3e35ab0852d6779403ada84b1f1be03692f507a";
      fetchSubmodules = false;
      sha256 = "sha256-1GUs+lyOwMDcCK3P88p7HH9R49hG3vTpR5keCbc6hY4=";
    };
    date = "2021-11-15";
  };
  fish-ghq = {
    pname = "fish-ghq";
    version = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-ghq";
      rev = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
      fetchSubmodules = false;
      sha256 = "sha256-6b1zmjtemNLNPx4qsXtm27AbtjwIZWkzJAo21/aVZzM=";
    };
    date = "2021-07-16";
  };
}
